### ISSUE TITLE
Audience Look Feedback Not Working

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-renewedvision-propresenter#123]
When utilizing the feedback for audience look, it works when the module is first initialized, but does not update as the look is changed in propresenter.  The actions related to audience look do what is expected, but the feedback does not update as the look is changed.

**Comment by greyshirtguy** [comment]
yeah - that is a limitation in the old (reverse engineered) API - it literally has no live updates of current look.
I added a "workaround" solution some time ago - to enable the module to continuosly "poll" the live look.....It's off by default because polling is not very elegant.  I've been using it for months - feel free to turn it on!
![image](https://user-images.githubusercontent.com/1886513/168403858-db0e40f8-e85c-4d92-8952-487680403f51.png)

This is mentioned in the help that very few people discover/read - click the little ? icon to open the help
![image](https://user-images.githubusercontent.com/1886513/168403905-398abce4-e603-4d7b-ac84-7a8c57a4b44d.png)

**Comment by greyshirtguy** [comment]
(yes, the new API will allow me to updates the look feedback in a more elegant way - that is on the todo list!!)
