### ISSUE TITLE
ProPresenter connection crashes companion when active presentation has more than 10 slides

### ISSUE THREAD

**Issue by BeulahSysAdmin** [bitfocus/companion-module-renewedvision-propresenter#157]
**Describe the bug/issue**
companion crashes and entirely reloads if a ProPresenter presentation with more than 10 or so slides is active. Once the presentation is cleared, companion is usable again. Admin interface is no longer accessible, satellite instance disconnects, and buttons are unusable on attached streamdeck control surface. This only happens when the active presentation has at least 10 slides. Logs show that companionPi crashes with the error "TypeError: Cannot read property 'presentationName' of undefined". Logs attached for more info. Also the issue only started happening once we updated ProPresenter to the latest update, v7.13.

**To Reproduce**
1. configure a connection with the propresenter module so that it's connected
2. trigger a slide in a presentation that has 10 or more slides (with companion or manually in ProPresenter)
3. Companion crashes
4. clearing the propresenter presentation or triggering a slide in a presentation with fewer slides will allow companion to reload.
5. see logs for more details.

**Expected behavior**
Companion should run and not crash.

**Versions/Environment (please complete the following information):**
 - ProPresenter 7.13
 - OS of ProPresenter Machine - MacOS 13
 - Companion Version - 2.4.2
 - OS of Companion machine - Raspberry Pi 4 running CompanionPi, updated to v2.4.2 with companion-update
 - Debug log output when issue occurs (Turn on debug log) - attached 

**Any Other Context*
Since companion is crashing, the web UI logs are lost every time. However when connecting to the companionPi via ssh, I was able to view the logs using journalctl, where I was able to find what was actually happening and locate the error reported above. I've attached a snippet of the logs that shows a couple of the crashes. Disconnecting/Disabling the ProPresenter module allows us to keep using companion without issue. 

[companion-log.txt](https://github.com/bitfocus/companion-module-renewedvision-propresenter/files/11288514/companion-log.txt)

**Comment by greyshirtguy** [comment]
I think this is a new issue with Pro 7.13
I found turning off the "Send Presentation Info Requests To ProPresenter" in the workaround settings is a workaround.
I think Pro7.13 is crashing it's websocket sometimes - when trying to build slide thumbnail data in response to sending those requests... you can live without them...(you loose some feedback that not many people even know about/use).
It's always been a touchy area - and really the best way forward is to for a new module that stops using hte old websocket and moves 100% to the new API
Yes - this is in the works - someone has already built the skeleton of the module (because I was too slow!) - I'll contribute to that when I get some free time in the next few weeks
![image](https://user-images.githubusercontent.com/1886513/233503678-081fad81-7b38-42b3-9f73-568e678b3117.png)

**Comment by BeulahSysAdmin** [comment]
Thanks for mentioning the workaround, I didn't make the connection that it would fix. Changing that setting to No has prevented the module from crashing and allows us to keep using the module for now. I did see the skeleton of the new module started that uses the REST API that Renewed Vision published, I'll definitely be following the progress as time moves forward. I did get a next slide trigger working via the REST API using a generic HTTP module, and could build out more if need be, but I think we are at a place where we are back to an equivalent level of functionality compared to before the 7.13 update. We'll revisit things when the new API based module is ready for use. Thanks for the assistance.
