### ISSUE TITLE
Feature Request: Current presentation on announcement layer

### ISSUE THREAD

**Issue by tmdarlan** [bitfocus/companion-module-renewedvision-propresenter#41]
It would be great if the dynamic variable "$(propresenter:presentation_name)" would point to the current presentation on the slide layer. Then make a new dynamic variable for presentations on the Announcement layer. Currently this variable changes between the 2 concurrently running presentations. I assume it points to the presentation with the most recent slide change.

**Comment by greyshirtguy** [comment]
At the moment - I can't see anything in the Pro7 remote protocol that indicates if a presetation is targeted to the announcements layer!
At this point in time, the best we could do is try and avoid updating $(propresenter:presentation_name) when presentations on the Announcement layer are triggered (not sure if/how - I'll look into it).

P.S. My gut-feeling (wild guess) is that RV will soon improve the remote app and therefore the protocol.... I hope so anyway! - because we could solve a few problems and do a lot more!
