### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by srmorris2** [bitfocus/companion-module-renewedvision-propresenter#8]
I would love to be able to show video remaining time on a button on the stream deck. I understand though that this would need to come via the stage display connection, and not the ProRemote connection.

**Comment by greyshirtguy** [comment]
Hmm, on the surface this sounds quite do-able.  It would be a quite a pervasive change (new settings for stage display password and port, as well as requiring the module to maintain two separate web socket connections).
With such a change, I wonder who is the "owner" of this module and could approve such a change.

I'm happy to do this sometime in the next few weeks in my own fork (after some code cleanup I need to do!) and submit a pull request to see if it gets accepted.

**Comment by monoxane** [comment]
I think i’m technically the owner but i’ve kinda disappeared for a bit because life is making it hard for me to do things like this right now, my main concern with this is how companion core would display text, maybe just have a json variable structure that can be written to via a module or an http api that can then be used in button names

**Comment by greyshirtguy** [comment]
I was just going to add a new dynamic variable (since they can be displayed in button labels).
I have already done that for the normal timers - it works well.
I could envision a button start starts a video...with the first line being the video name and the second line being the video countdown timer....When you tap it, the video starts and the button shows the countdown time...

**Comment by monoxane** [comment]
Oh okay i totally missed the fact that you could display vars on buttons now, go ahead

**Comment by greyshirtguy** [comment]
Thanks!  - Will Do. I've also promised to cleanup some code. Both will take some time - probably a few weeks (I know the busy life feeling well!).

**Comment by greyshirtguy** [comment]
Progress Update: 
* Code cleanup is complete.
* Now have a "working first revision" of code to connect to stage display and get video countdown timer.  I have button that show video countdown.
* Performing testing and fine tuning of the module behavior for if and when stage display connection is not available/fails/password is wrong/etc

**Comment by greyshirtguy** [comment]
Code tested. Doco updated. Pull request submitted.

**Comment by JeffreyDavidsz** [comment]
Updated into core, thanks for all the work!
