### ISSUE TITLE
Is there any other way to do this ???

### ISSUE THREAD

**Issue by pilgrims1** [bitfocus/companion-module-renewedvision-propresenter#86]
1. Next Previous item in Current PlayList or Library.
2. Next Previous Background in current Media List.
3. Next previous Media List in Media.
4. Custom Action how to ???

how can I  this ???

**Comment by greyshirtguy** [comment]
Hello!

We can only send commands to Pro7 that Pro7 understands in it's remote protocol.
There are no commands in the remote protocol for those items you listed in 1. 2. and  3.

You can however, send MIDI notes to Pro7 to achieve much of what you are wanting.....(using MIDI relay Companion module and with MIDI-relay listener program installed and running on machine with Pro7.)

![image](https://user-images.githubusercontent.com/1886513/129284818-91c3b948-1d84-447a-a933-521b3a2e82d3.png)


The custom action does NO magic - you can make up new features/actions that Pro7 does not already do.
The reason I have added that to the module is so that there is a way to make buttons that support any NEW features that get added to Pro7 remote protocol *before* the Companion module is updated to support those new features.

It took me  acouple of weeks to update the module to add triggering macros and looks - all that time, anyone could have used custom action to trigger macros and looks (if they asked me what is the custom action to type there).
It's really a support option for me to help people if they want  a new feature in a rush before the Companiopn app is updated.

**Comment by pilgrims1** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you for your showing ways....

--------- 원본 메일 ---------

    
        보낸사람: greyshirtguy ***@***.***>
        받는사람: bitfocus/companion-module-renewedvision-propresenter ***@***.***>
        
            참조: pilgrims1 ***@***.***>, Author ***@***.***>
        
        날짜: 21.08.13 09:05 GMT +0900
        제목: Re: [bitfocus/companion-module-renewedvision-propresenter] Is there any other way to do this ??? (#86)
        
        
    
    
        
Hello!
We can only send commands to Pro7 that Pro7 understands in it's remote protocol.
There are no commands in the remote protocol for those items you listed in 1. 2. and  3.
You can however, send MIDI notes to Pro7 to achieve much of what you are wanting.....(using MIDI relay Companion module and with MIDI-relay listener program installed and running on machine with Pro7.)

The custom action does NO magic - you can make up new features/actions that Pro7 does not already do.
The reason I have added that to the module is so that there is a way to make buttons that support any NEW features that get added to Pro7 remote protocol before the Companion module is updated to support those new features.
It took me  acouple of weeks to update the module to add triggering macros and looks - all that time, anyone could have used custom action to trigger macros and looks (if they asked me what is the custom action to type there).
It's really a support option for me to help people if they want  a new feature in a rush before the Companiopn app is updated.
